data_dict = {
    "excel": "Data Analytics",
    "tableau": "Data Analytics",
    "power bi": "Data Analytics",
    "powerbi": "Data Analytics",
    "grafana": "Data Analytics",
    "qlikview": "Data Analytics",
    "google analytics": "Data Analytics",
    "superset": "Data Analytics",
    "looker": "Data Analytics",
    "pandas": "Data Analytics",
    "impala": "Data Analytics",
    "d3.js": "Data Analytics",
    "jupyter": "Data Science and Machine Learning",
    "anaconda": "Data Science and Machine Learning",
    "scikit-learn": "Data Science and Machine Learning",
    "tensorflow": "Data Science and Machine Learning",
    "keras": "Data Science and Machine Learning",
    "pytorch": "Data Science and Machine Learning",
    "jax": "Data Science and Machine Learning",
    "langchain": "Data Science and Machine Learning",
    "mxnet": "Data Science and Machine Learning",
    "caffe": "Data Science and Machine Learning",
    "theano": "Data Science and Machine Learning",
    "openai gym": "Data Science and Machine Learning",
    "automl": "Data Science and Machine Learning",
    "caret": "Data Science and Machine Learning",
    "numpy": "Data Science and Machine Learning",
    "matplotlib": "Data Science and Machine Learning",
    "streamlit": "Data Science and Machine Learning",
    "plotly": "Data Science and Machine Learning",
    "seaborn": "Data Science and Machine Learning",
    "sql": "Programming Languages",
    "nosql": "Databases",
    "hive": "Databases",
    "pig": "Data Science and Machine Learning",
    "scrapy": "Data Science and Machine Learning",
    "beautifulsoup": "Data Science and Machine Learning",
    "selenium": "Data Science and Machine Learning",
    "pyspark": "Data Science and Machine Learning",
    "hadoop": "Data Engineering",
    "spark": "Data Engineering",
    "airflow": "Data Engineering",
    "kafka": "Data Engineering",
    "postgresql": "Databases",
    "parquet": "Databases",
    "mysql": "Databases",
    "oracle database": "Databases",
    "sql server": "Databases",
    "t-sql": "Databases",
    "mongodb": "Databases",
    "cassandra": "Databases",
    "redis": "Databases",
    "redshift": "Databases",
    "google bigquery": "Databases",
    "hbase": "Databases",
    "sqlite": "Databases",
    "neo4j": "Databases",
    "derby": "Databases",
    "couchbase": "Databases",
    "ibm db2": "Databases",
    "mariadb": "Databases",
    "teradata": "Databases",
    "vertica": "Databases",
    "aurora": "Databases",
    "ignite": "Databases",
    "dynamodb": "Databases",
    "cockroachdb": "Databases",
    "influxdb": "Databases",
    "ravendb": "Databases",
    "arangodb": "Databases",
    "cosmos db": "Databases",
    "firebase": "Databases",
    "cratedb": "Databases",
    "memcached": "Databases",
    "clickhouse": "Databases",
    "hana": "Databases",
    "timescaledb": "Databases",
    "marklogic": "Databases",
    "voltdb": "Databases",
    "spanner": "Databases",
    "presto": "Databases",
    "tidb": "Databases",
    "riak": "Databases",
    "orientdb": "Databases",
    "hdfs": "Databases",
    "kudu": "Databases",
    "h2": "Databases",
    "hsqldb": "Databases",
    "hazelcast": "Databases",
    "greenplum": "Databases",
    "exasol": "Databases",
    "ibm informix": "Databases",
    "pulsar": "Databases",
    "neptune": "Databases",
    "firestore": "Databases",
    "arctic": "Databases",
    "hyperledger fabric": "Databases",
    "documentdb": "Databases",
    "datastore": "Databases",
    "ase": "Databases",
    "pinot": "Databases",
    "qlik sense": "Databases",
    "alibaba cloud analyticdb": "Databases",
    "memsql": "Databases",
    "bigtable": "Databases",
    "timesten": "Databases",
    "oracle nosql database": "Databases",
    "timestream": "Databases",
    "aerospike": "Databases",
    "questdb": "Databases",
    "rockset": "Databases",
    "rocksdb": "Databases",
    "skysql": "Databases",
    "astradb": "Databases",
    "yugabyte db": "Databases",
    "aiven for kafka": "Databases",
    "kairosdb": "Databases",
    "druid": "Databases",
    "actian vector": "Databases",
    "singlestore": "Databases",
    "esgyndb": "Databases",
    "scylladb": "Databases",
    "vitess": "Databases",
    "tikv": "Databases",
    "keyspaces": "Databases",
    "nuodb": "Databases",
    "hawkular": "Databases",
    "griddb": "Databases",
    "memorystore": "Databases",
    "ibm db2 warehouse": "Databases",
    "redisgraph": "Databases",
    "tarantool": "Databases",
    "grafana loki": "Databases",
    "expero driven": "Databases",
    "chaosdb": "Databases",
    "flink": "Databases",
    "prometheus": "Databases",
    "graphdb": "Databases",
    "python": "Programming Languages",
    "r": "Programming Languages",
    "matlab": "Programming Languages",
    "julia": "Programming Languages",
    "java": "Programming Languages",
    "scala": "Programming Languages",
    "c++": "Programming Languages",
    "sas": "Programming Languages",
}


webdev_dict = {
    # Programming Languages
    "HTML": "Programming Languages",
    "CSS": "Programming Languages",
    "JavaScript": "Programming Languages",
    "TypeScript": "Programming Languages",
    "Python": "Programming Languages",
    "Ruby": "Programming Languages",
    "PHP": "Programming Languages",
    "Java": "Programming Languages",
    "C#": "Programming Languages",
    "Go": "Programming Languages",
    "Rust": "Programming Languages",
    "Kotlin": "Programming Languages",
    "Swift": "Programming Languages",
    "Perl": "Programming Languages",
    "Scala": "Programming Languages",
    "Groovy": "Programming Languages",
    "Clojure": "Programming Languages",
    "Haskell": "Programming Languages",
    "Lua": "Programming Languages",
    "Elixir": "Programming Languages",
    "C++": "Programming Languages",
    "C": "Programming Languages",
    "Objective-C": "Programming Languages",
    "R": "Programming Languages",
    "Shell": "Programming Languages",
    "PowerShell": "Programming Languages",
    "Bash": "Programming Languages",
    "Julia": "Programming Languages",
    "Dart": "Programming Languages",
    # Frontend
    "React": "Frontend",
    "Angular": "Frontend",
    "Vue.js": "Frontend",
    "Bootstrap": "Frontend",
    "Sass": "Frontend",
    "Less": "Frontend",
    "Styled Components": "Frontend",
    "Tailwind CSS": "Frontend",
    "Material-UI": "Frontend",
    "Emotion": "Frontend",
    "jQuery": "Frontend",
    "Webpack": "Frontend",
    "Babel": "Frontend",
    "Flow": "Frontend",
    "Ember.js": "Frontend",
    "Backbone.js": "Frontend",
    "Polymer": "Frontend",
    "Gatsby": "Frontend",
    "Next.js": "Frontend",
    "Nuxt.js": "Frontend",
    "Jasmine": "Frontend",
    "Mocha": "Frontend",
    "Enzyme": "Frontend",
    "Cypress": "Frontend",
    "Jest": "Frontend",
    "TestCafe": "Frontend",
    "Puppeteer": "Frontend",
    "Storybook": "Frontend",
    "Gulp": "Frontend",
    "Grunt": "Frontend",
    "Parcel": "Frontend",
    "ESLint": "Frontend",
    "Prettier": "Frontend",
    "Husky": "Frontend",
    "Lint-Staged": "Frontend",
    "Stylelint": "Frontend",
    "Hugo": "Frontend",
    "Docusaurus": "Frontend",
    "11ty": "Frontend",
    "Grommet": "Frontend",
    "Chakra UI": "Frontend",
    "Ant Design": "Frontend",
    "Foundation": "Frontend",
    "UIKit": "Frontend",
    "PrimeReact": "Frontend",
    "Quasar": "Frontend",
    "Vuetify": "Frontend",
    # Backend
    "Django": "Backend",
    "Flask": "Backend",
    "Express.js": "Backend",
    "Ruby on Rails": "Backend",
    "ASP.NET": "Backend",
    "Spring Boot": "Backend",
    "Node.js": "Backend",
    "Laravel": "Backend",
    "Symfony": "Backend",
    "Grails": "Backend",
    "Hibernate": "Backend",
    "Play Framework": "Backend",
    "ASP.NET Core": "Backend",
    "FastAPI": "Backend",
    "NestJS": "Backend",
    "Phoenix": "Backend",
    "CodeIgniter": "Backend",
    "CakePHP": "Backend",
    "Slim": "Backend",
    "Gin": "Backend",
    "Echo": "Backend",
    "FuelPHP": "Backend",
    "Vapor": "Backend",
    "Dancer": "Backend",
    "Catalyst": "Backend",
    # Fullstack
    "MEAN": "Fullstack",
    "MERN": "Fullstack",
    "LAMP": "Fullstack",
    "JHipster": "Fullstack",
    "LoopBack": "Fullstack",
    "Sails": "Fullstack",
    "Adonis": "Fullstack",
    "Feathers": "Fullstack",
    "React Native": "Fullstack",
    "Flutter": "Fullstack",
    "Ionic": "Fullstack",
    "Xamarin": "Fullstack",
    "PhoneGap": "Fullstack",
    "Cordova": "Fullstack",
}


devops_dict = {
    "aws": "Cloud Computing",
    "azure": "Cloud Computing",
    "gcp": "Cloud Computing",
    "ibm cloud": "Cloud Computing",
    "snowflake": "Cloud Computing",
    "databricks": "Cloud Computing",
    "oracle cloud": "Cloud Computing",
    "elatic cloud": "Cloud Computing",
    "Jenkins": "DevOps",
    "Ansible": "DevOps",
    "Docker": "DevOps",
    "Kubernetes": "DevOps",
    "Git": "DevOps",
    "Chef": "DevOps",
    "Puppet": "DevOps",
    "Terraform": "DevOps",
    "Prometheus": "DevOps",
    "Grafana": "DevOps",
    "ELK Stack": "DevOps",
    "Splunk": "DevOps",
    "AWS CloudFormation": "DevOps",
    "Azure DevOps": "DevOps",
    "Google Cloud Deployment Manager": "DevOps",
    "CircleCI": "DevOps",
    "Travis CI": "DevOps",
    "TeamCity": "DevOps",
    "Jira": "DevOps",
    "Confluence": "DevOps",
    "Bitbucket": "DevOps",
    "New Relic": "DevOps",
    "Datadog": "DevOps",
    "GitHub Actions": "DevOps",
    "GitLab CI/CD": "DevOps",
    "Artifactory": "DevOps",
    "Nagios": "DevOps",
    "Zabbix": "DevOps",
    "SonarQube": "DevOps",
    "Selenium": "DevOps",
    "JFrog": "DevOps",
    "Vault": "DevOps",
    "Packer": "DevOps",
    "Gradle": "DevOps",
    "Maven": "DevOps",
    "TFS": "DevOps",
    "Octopus Deploy": "DevOps",
    "Spinnaker": "DevOps",
    "Rundeck": "DevOps",
    "Consul": "DevOps"
    # Add more tools as needed
}
